jobs:
- job: BuildAndNotify
  displayName: 'Build and Notify on Failure'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self 
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: npm run build
    displayName: 'npm run build'

  - task: PowerShell@2
    displayName: 'Send Email Notification'
    condition: failed()  # Send email only on failure
    inputs:
      targetType: 'inline'
      script: |
        $emailFrom = "sarthakpokhrel8example.com"
        $emailTo = "sarthakpokhrel3@email.com"
        $smtpServer = "smtp.gmail.com"  # Replace with your SMTP server address
        $smtpUsername = "sarthakpokhrel8"  # Replace with your SMTP username (if required)
        $smtpPassword = "esvpvqnydnstlryw"


        $subject = "Azure Pipeline Build Failed"
        $body = "The build for branch $(Build.SourceBranch) in pipeline $(System.DefinitionName) has failed. Check details at $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

        $smtpClient = New-Object Net.Mail.SmtpClient($smtpServer)
        $smtpClient.EnableSsl = $true
        $smtpClient.Credentials = New-Object System.Net.NetworkCredential($smtpUsername, $smtpPassword)
        $smtpClient.Send($emailFrom, $emailTo, $subject, $body)
